version: 2.1

workflows:
  build-and-test:
    jobs:
      - build
orbs:
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  build:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout
      - run:
          name: Install dependecies
          command: npm install
      - run:
          name: Build
          command: npm run build
